//AUTH
export const LOGIN_SUCCESS ='LOGIN_SUCCESS'
export const LOGOUT_SUCCESS ='LOGOUT_SUCCESS'
export const START_LOADING ='START_LOADING'
export const REGISTER_SUCCESS ='REGISTER_SUCCESS'
export const LOGIN_FAIL ='LOGIN_FAIL'


//POST
export const GET_POSTS ='GET_POSTS'
export const GET_FAVORITE_POST ='GET_FAVORITE_POST'
export const ADD_FAVORITE_POST ='ADD_FAVORITE_POST'
export const GET_PERSONAL_POST ='GET_PERSONAL_POST'
export const ADD_NEW_POST ='ADD_NEW_POST'

